---
- name: include multisite checks
  include: checks.yml

# Include the tasks depending on the zone type
- name: include master multisite tasks
  include: master.yml
  when: "rgw_zonemaster is defined and rgw_zonemaster"
  # Hard code this so we will skip the entire file instead of individual tasks (Default isn't Consistent)
  static: False

- name: include secondary multisite tasks
  include: secondary.yml
  when: "rgw_zonesecondary is defined and rgw_zonesecondary"
  # Hard code this so we will skip the entire file instead of individual tasks (Default isn't Consistent)
  static: False

# regexp: "{{ ansible_host }}"
# Continue with common tasks
- name: add zone to rgw stanza in ceph.conf
  lineinfile:
    dest: "/etc/ceph/{{ cluster }}.conf"
    regexp: "^rgw_zone ="
    insertafter: '^\[client.rgw.{{ ansible_hostname }}\]'
    line: "rgw_zone = {{ rgw_zone }}"
    state: present
  notify:
    - restart rgw
